/** Метка версии безопасности — видна в GET /api/health (для проверки деплоя). */
module.exports = {
  stage: 'J-H',
  textSanitization: true,
  photoMimeStrict: true,
  healthNoBucketName: true,
  healthMinimalPaymentInfo: true,
  activeVerifySessionRequired: true,
  paymentStatusOwnerCheck: true,
  robokassaCallbackIdempotent: true,
  robokassaNoRedirectSecretFallback: true,
  mobileIdWebhookStrict: true,
  checkPhoneRateLimit: true,
  checkPhoneNoUserName: true,
  pinAccountLockout: true,
  sessionLogout: true,
  sessionHttpOnlyCookie: true,
  verifySessionTokenHeader: true,
  verifyCodeRateLimit: true,
  partnersNextCodeClosed: true,
  corsRestricted: true,
  corsCredentials: true,
  userSessionAuth: true,
  legacyAdminSecretRemoved: true,
  apiRateLimit: true,
  apiRateLimitMax: 1000,
  authRateLimitMax: 120,
  adminAuthVerifyRateLimit: true,
  deployRateLimit: true,
  registrationPinRequiredForUpdate: true,
  dailyDbBackup: true,
};
